export default function SqlFormatterBeautifierSeo() {
  return (
    <div className="max-w-4xl mx-auto space-y-12">
      {/* How It Works */}
      <section className="space-y-4">
        <h2 className="text-2xl font-bold text-foreground">How It Works</h2>
        <div className="prose prose-neutral dark:prose-invert">
          <p className="text-muted-foreground">
            This SQL formatter beautifies raw, minified SQL queries by adding proper indentation,
            line breaks, and keyword capitalization for improved readability.
          </p>
          <p className="text-muted-foreground">
            The formatting process:
          </p>
          <ol className="text-muted-foreground space-y-2 list-decimal list-inside">
            <li><strong className="text-foreground">Tokenization:</strong> The SQL is broken into tokens - keywords, identifiers, operators, literals, and comments.</li>
            <li><strong className="text-foreground">Structure analysis:</strong> The formatter identifies SQL clauses (SELECT, FROM, WHERE) and nesting levels (parentheses, subqueries).</li>
            <li><strong className="text-foreground">Indentation application:</strong> Based on nesting depth, appropriate indentation is added to each line.</li>
            <li><strong className="text-foreground">Keyword formatting:</strong> SQL keywords are capitalized consistently, and spacing around operators is standardized.</li>
          </ol>
          <p className="text-muted-foreground">
            Well-formatted SQL is easier to read, debug, and maintain. Complex queries with
            multiple joins and subqueries become comprehensible when properly formatted.
          </p>
        </div>
      </section>

      {/* When You'd Actually Use This */}
      <section className="space-y-4">
        <h2 className="text-2xl font-bold text-foreground">When You'd Actually Use This</h2>
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
          {[
            {
              title: "Debugging Complex Queries",
              description: "Format minified SQL from logs or error messages to understand what's actually being executed."
            },
            {
              title: "Code Review Preparation",
              description: "Beautify SQL before code reviews so reviewers can focus on logic rather than deciphering formatting."
            },
            {
              title: "ORM Query Inspection",
              description: "Format SQL generated by ORMs to understand what queries are actually being sent to the database."
            },
            {
              title: "Documentation Creation",
              description: "Make SQL examples in documentation readable and professional-looking."
            },
            {
              title: "Learning SQL",
              description: "Format example queries to better understand SQL structure and clause relationships."
            },
            {
              title: "Query Optimization",
              description: "Format queries before analyzing execution plans to clearly see join order and structure."
            },
          ].map((item, idx) => (
            <div key={idx} className="rounded-lg border bg-muted/30 p-4 space-y-2">
              <h3 className="font-semibold text-foreground">{item.title}</h3>
              <p className="text-sm text-muted-foreground">{item.description}</p>
            </div>
          ))}
        </div>
      </section>

      {/* What to Know Before Using */}
      <section className="space-y-4">
        <h2 className="text-2xl font-bold text-foreground">What to Know Before Using</h2>
        <div className="space-y-3">
          {[
            {
              caveat: "Formatting is cosmetic only",
              explanation: "The formatted SQL executes identically to the original. Formatting affects human readability, not database performance."
            },
            {
              caveat: "Different formatters produce different results",
              explanation: "Indentation style, keyword case, and line break placement vary between formatters. Choose one style and be consistent."
            },
            {
              caveat: "Very long lines may still be long",
              explanation: "Column lists with many fields or long string literals may still create wide output. Some manual adjustment may be needed."
            },
            {
              caveat: "Comments are preserved but may move",
              explanation: "SQL comments are kept but may shift position during formatting. Critical comment placement should be verified after formatting."
            },
            {
              caveat: "Vendor-specific syntax may not be recognized",
              explanation: "Standard SQL is well-supported. Proprietary extensions from specific databases may not format perfectly."
            },
          ].map((item, idx) => (
            <div key={idx} className="rounded-lg border bg-muted/30 p-4">
              <h3 className="font-semibold text-foreground mb-1">{item.caveat}</h3>
              <p className="text-sm text-muted-foreground">{item.explanation}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Common Questions */}
      <section className="space-y-4">
        <h2 className="text-2xl font-bold text-foreground">Common Questions</h2>
        <div className="space-y-6">
          {[
            {
              question: "What's the difference between formatting and minifying?",
              answer: "Formatting adds whitespace for readability. Minifying removes whitespace to reduce size. Format for development, minify for production SQL that's generated dynamically."
            },
            {
              question: "Does formatting affect query performance?",
              answer: "No. The database receives the same logical query regardless of formatting. Performance is determined by query structure, indexes, and data - not whitespace."
            },
            {
              question: "What indentation style is best?",
              answer: "Common choices: 2 spaces (compact), 4 spaces (traditional), or tabs (configurable). Choose based on team standards. Consistency matters more than the specific choice."
            },
            {
              question: "Should SQL keywords be uppercase or lowercase?",
              answer: "Both work. UPPERCASE makes keywords stand out. lowercase is easier to type. Proper Case is a middle ground. Pick one and be consistent within your codebase."
            },
            {
              question: "Can this format stored procedures?",
              answer: "Basic formatting works, but complex procedural SQL (loops, conditionals) may not format perfectly. Dedicated PL/SQL formatters handle procedural code better."
            },
            {
              question: "How do I format SQL in my code editor?",
              answer: "Many editors have SQL formatting extensions (Prettier, SQL Formatter). Database IDEs like DataGrip have built-in formatters. This tool works standalone in any browser."
            },
            {
              question: "What about very long queries?",
              answer: "Long queries format fine but may produce very long output. Consider breaking complex queries into CTEs (Common Table Expressions) for better structure."
            },
          ].map((item, idx) => (
            <div key={idx} className="space-y-2">
              <h3 className="font-semibold text-foreground">{item.question}</h3>
              <p className="text-muted-foreground">{item.answer}</p>
            </div>
          ))}
        </div>
      </section>
    </div>
  )
}
