import React from "react";

export function RandomColorPaletteGeneratorSEO() {
  return (
    <section className="mt-12 space-y-8">
      <div>
        <h2 className="text-2xl font-semibold tracking-tight mb-4">
          What This Random Generator Does
        </h2>
        <p className="text-muted-foreground">
          Instantly generates completely random color palettes with 2-12 colors. No rules, no harmony constraints — just pure randomness for when you need inspiration or placeholder colors fast. Lock colors you like and regenerate the rest until you find a combination that works.
        </p>
      </div>

      <div>
        <h2 className="text-2xl font-semibold tracking-tight mb-4">
          How Random Color Generation Works
        </h2>
        <p className="text-muted-foreground mb-4">
          Each color is generated by picking random RGB values between 0-255. This means any color in the 16.7 million color hex space is equally likely — from pure black to pure white and everything between. The lock feature lets you keep specific colors while randomizing others.
        </p>
        <div className="p-4 rounded-lg border bg-card">
          <h3 className="font-medium mb-2">The math behind the randomness</h3>
          <p className="text-sm text-muted-foreground mb-2">
            Each color channel (R, G, B) gets a random integer from 0-255:
          </p>
          <pre className="bg-muted p-3 rounded text-xs font-mono overflow-x-auto">
            {`R = random(0, 255) = 137
G = random(0, 255) = 42  
B = random(0, 255) = 201
Result: #892ac9`}
          </pre>
          <p className="text-sm text-muted-foreground mt-2">
            This gives 256³ = 16,777,216 possible colors. Each generation has a 1 in 16.7 million chance of producing any specific color.
          </p>
        </div>
      </div>

      <div>
        <h2 className="text-2xl font-semibold tracking-tight mb-4">
          When Random Palettes Are Actually Useful
        </h2>
        <div className="space-y-4">
          <div className="p-4 rounded-lg border bg-card">
            <h3 className="font-medium mb-2">Breaking Creative Block</h3>
            <p className="text-sm text-muted-foreground">
              A designer is stuck on a project. They generate random palettes until one sparks an idea — not to use directly, but to break out of their usual color habits. The unexpected combination suggests a direction they hadn't considered.
            </p>
          </div>
          <div className="p-4 rounded-lg border bg-card">
            <h3 className="font-medium mb-2">Placeholder Colors for Mockups</h3>
            <p className="text-sm text-muted-foreground">
              Someone is building a wireframe and needs colors to distinguish sections. Random generation is faster than carefully picking colors that will just be replaced later. The client sees the layout without getting distracted by "final" colors.
            </p>
          </div>
          <div className="p-4 rounded-lg border bg-card">
            <h3 className="font-medium mb-2">Testing Color Agnostic Designs</h3>
            <p className="text-sm text-muted-foreground">
              A developer wants to ensure their UI works with any color scheme. They rapidly generate random palettes and apply them to their components. If the design breaks with certain combinations, they know they have contrast or hierarchy issues to fix.
            </p>
          </div>
          <div className="p-4 rounded-lg border bg-card">
            <h3 className="font-medium mb-2">Learning Color Relationships</h3>
            <p className="text-sm text-muted-foreground">
              A design student generates random palettes and analyzes why some "work" and others clash. They lock one color at a time and regenerate to see what combinations emerge. It's a hands-on way to develop color intuition.
            </p>
          </div>
          <div className="p-4 rounded-lg border bg-card">
            <h3 className="font-medium mb-2">Generative Art Projects</h3>
            <p className="text-sm text-muted-foreground">
              An artist is creating algorithmic art where colors are part of the randomness. They generate palettes programmatically, using this tool to prototype the color generation logic before coding it into their artwork.
            </p>
          </div>
          <div className="p-4 rounded-lg border bg-card">
            <h3 className="font-medium mb-2">A/B Test Variant Generation</h3>
            <p className="text-sm text-muted-foreground">
              A marketer needs multiple color variants for button A/B tests. Instead of manually creating variations, they generate random palettes, pick the distinct ones, and test them to see which performs best with real users.
            </p>
          </div>
        </div>
      </div>

      <div>
        <h2 className="text-2xl font-semibold tracking-tight mb-4">
          How to Use the Lock Feature
        </h2>
        <div className="space-y-3 text-muted-foreground">
          <p>
            <strong>Lock colors you want to keep.</strong> Click the lock icon on any color swatch. Locked colors stay fixed when you click Regenerate — only unlocked colors change.
          </p>
          <p>
            <strong>Build palettes iteratively.</strong> Generate until you find one color you like. Lock it. Regenerate until you find a second color that works with the first. Lock it. Continue until you have a complete palette.
          </p>
          <p>
            <strong>Test color compatibility.</strong> Lock your brand color, then regenerate to see what random colors happen to work with it. You might discover unexpected accent colors that complement your brand.
          </p>
          <p>
            <strong>Unlock to start fresh.</strong> Click the lock icon again to unlock a color. Or hit "Generate New" to completely reset and start over.
          </p>
        </div>
      </div>

      <div>
        <h2 className="text-2xl font-semibold tracking-tight mb-4">
          Export Formats
        </h2>
        <div className="grid sm:grid-cols-3 gap-4">
          <div className="p-4 rounded-lg border bg-card">
            <h3 className="font-medium mb-2">CSS Variables</h3>
            <pre className="bg-muted p-2 rounded text-xs font-mono overflow-x-auto mt-2">
              {`:root {
  --color-1: #8b5cf6;
  --color-2: #3b82f6;
  --color-3: #22c55e;
}`}
            </pre>
            <p className="text-sm text-muted-foreground mt-2">
              Drop into your CSS. Use as {`var(--color-1)`}.
            </p>
          </div>
          <div className="p-4 rounded-lg border bg-card">
            <h3 className="font-medium mb-2">Tailwind Config</h3>
            <pre className="bg-muted p-2 rounded text-xs font-mono overflow-x-auto mt-2">
              {`colors: {
  palette: {
    1: '#8b5cf6',
    2: '#3b82f6',
    3: '#22c55e',
  }
}`}
            </pre>
            <p className="text-sm text-muted-foreground mt-2">
              Extend your Tailwind theme. Use as {`bg-palette-1`}.
            </p>
          </div>
          <div className="p-4 rounded-lg border bg-card">
            <h3 className="font-medium mb-2">JSON Array</h3>
            <pre className="bg-muted p-2 rounded text-xs font-mono overflow-x-auto mt-2">
              {`["#8b5cf6", "#3b82f6", "#22c55e"]`}
            </pre>
            <p className="text-sm text-muted-foreground mt-2">
              Import into JavaScript projects or design tools.
            </p>
          </div>
        </div>
      </div>

      <div>
        <h2 className="text-2xl font-semibold tracking-tight mb-4">
          Tips for Better Random Results
        </h2>
        <div className="space-y-3 text-muted-foreground">
          <p>
            <strong>Don't expect perfection on the first try.</strong> True randomness means most generations will be mediocre. The value is in volume — generate 20 palettes, and one might surprise you.
          </p>
          <p>
            <strong>Use smaller palette sizes.</strong> Random 3-color palettes are more likely to be cohesive than random 10-color palettes. Start small, add colors as needed.
          </p>
          <p>
            <strong>Look for happy accidents.</strong> Sometimes a "bad" random palette has one interesting color relationship. Lock those colors and regenerate the rest to build around the accident.
          </p>
          <p>
            <strong>Consider adjusting saturation manually.</strong> Random generation can produce neon-bright or muddy colors. After finding a palette you like, use the Color Picker to adjust individual colors toward your preferred saturation level.
          </p>
          <p>
            <strong>Save anything you might use.</strong> Random palettes are ephemeral — if you generate something you like, export it immediately. Don't assume you'll regenerate it later.
          </p>
        </div>
      </div>

      <div>
        <h2 className="text-2xl font-semibold tracking-tight mb-4">
          Frequently Asked Questions
        </h2>
        <div className="space-y-4">
          <div>
            <h3 className="font-medium mb-2">Can I generate truly random colors, or is there a pattern?</h3>
            <p className="text-sm text-muted-foreground">
              The colors are pseudo-random using JavaScript's Math.random(). For design purposes, this is effectively random — there's no intentional pattern or bias. However, for cryptographic or security applications, this isn't suitable randomness.
            </p>
          </div>
          <div>
            <h3 className="font-medium mb-2">Why do I sometimes get very similar colors?</h3>
            <p className="text-sm text-muted-foreground">
              True randomness includes clustering — sometimes you'll get colors that are close together. If you want guaranteed variety, use the Color Harmony Generator or Custom Color Palette Generator with harmony modes instead.
            </p>
          </div>
          <div>
            <h3 className="font-medium mb-2">Can I generate only light or only dark random colors?</h3>
            <p className="text-sm text-muted-foreground">
              This tool generates across the full brightness range. For random colors constrained to specific lightness ranges, use the Color Palette Generator with a base color and lightness adjustments.
            </p>
          </div>
          <div>
            <h3 className="font-medium mb-2">How do I get the same palette again?</h3>
            <p className="text-sm text-muted-foreground">
              You can't — true randomness means you won't regenerate the same palette. If you like a palette, export or copy it immediately. Consider saving it in the Favorite Colors Manager for later access.
            </p>
          </div>
          <div>
            <h3 className="font-medium mb-2">Is there a way to seed the random generator?</h3>
            <p className="text-sm text-muted-foreground">
              No — this tool doesn't support seeded randomness. Every generation is independent. For reproducible random palettes, you'd need a tool with seed functionality.
            </p>
          </div>
          <div>
            <h3 className="font-medium mb-2">What's the maximum palette size?</h3>
            <p className="text-sm text-muted-foreground">
              The slider goes up to 12 colors. For larger random palettes, generate multiple smaller palettes and merge them using the Palette Merger tool.
            </p>
          </div>
          <div>
            <h3 className="font-medium mb-2">Can I use random palettes for production designs?</h3>
            <p className="text-sm text-muted-foreground">
              You can, but it's not recommended without review. Random colors don't consider accessibility, brand alignment, or color theory. Use random generation for exploration, then refine your chosen palette with purposeful tools.
            </p>
          </div>
        </div>
      </div>

      <div>
        <h2 className="text-2xl font-semibold tracking-tight mb-4">
          When to Use Random vs. Intentional Generation
        </h2>
        <div className="space-y-3 text-muted-foreground">
          <p>
            <strong>Use this Random Generator when</strong> you need quick placeholders, creative inspiration, or want to break out of color ruts without thinking about rules.
          </p>
          <p>
            <strong>Use the Color Harmony Generator when</strong> you want colors that work together based on color theory (complementary, analogous, triadic relationships).
          </p>
          <p>
            <strong>Use the Custom Color Palette Generator when</strong> you want harmony-based generation with the ability to lock individual colors and fine-tune results.
          </p>
          <p>
            <strong>Use the Color Picker when</strong> you have specific colors in mind and need precise control over hue, saturation, and lightness values.
          </p>
        </div>
      </div>
    </section>
  );
}

export default RandomColorPaletteGeneratorSEO;
