import React from "react"

export default function CronExpressionValidatorExplainerSeo() {
  return (
    <div className="w-full max-w-4xl mx-auto space-y-8">
      {/* How It Works */}
      <section className="space-y-4">
        <h2 className="text-2xl font-semibold">How CRON Validation and Explanation Works</h2>

        <div className="space-y-3 text-muted-foreground">
          <p>
            This validator checks each of the five CRON fields against valid ranges and syntax
            rules. It verifies that values fall within acceptable bounds (0-59 for minutes,
            0-23 for hours, etc.) and that special characters are used correctly.
          </p>

          <p>
            The explainer then translates each field into plain English, building a complete
            sentence that describes when the task runs. It handles all special characters:
            asterisks, ranges, lists, and step values.
          </p>

          <div className="rounded-lg border bg-muted/30 p-4 space-y-2">
            <p className="text-sm font-medium">Validation checks performed:</p>
            <ul className="list-disc list-inside space-y-1 text-sm">
              <li>Correct number of fields (5 or 6 depending on mode)</li>
              <li>Each field value within valid range</li>
              <li>Proper syntax for ranges (start-end)</li>
              <li>Valid step values (positive integers)</li>
              <li>Comma-separated lists contain only valid values</li>
              <li>No invalid characters or malformed expressions</li>
            </ul>
          </div>

          <p>
            The field breakdown tab shows detailed analysis of each position, explaining what
            constraint it imposes and whether it's valid. Invalid fields are highlighted with
            specific error messages.
          </p>
        </div>
      </section>

      {/* Specific Use Cases */}
      <section className="space-y-4">
        <h2 className="text-2xl font-semibold">When You'd Actually Use This</h2>

        <div className="grid gap-4 md:grid-cols-2">
          <div className="rounded-lg border bg-muted/30 p-4">
            <h3 className="font-medium mb-2">Debugging a CRON expression that isn't working</h3>
            <p className="text-sm text-muted-foreground">
              A developer copied a CRON expression from documentation but the job never runs.
              The validator reveals they used "24" for hour (valid range is 0-23) or included
              an extra space that broke parsing.
            </p>
          </div>

          <div className="rounded-lg border bg-muted/30 p-4">
            <h3 className="font-medium mb-2">Learning what a complex expression means</h3>
            <p className="text-sm text-muted-foreground">
              Someone inherited a codebase with "30 */4 1-15 * 1-5" and needs to understand
              it. The explainer breaks it down: "at minute 30, every 4 hours, days 1-15 of
              the month, Monday through Friday."
            </p>
          </div>

          <div className="rounded-lg border bg-muted/30 p-4">
            <h3 className="font-medium mb-2">Verifying expressions generated by code</h3>
            <p className="text-sm text-muted-foreground">
              A program dynamically builds CRON expressions based on user input. Before
              deploying to production, the team validates generated expressions to catch
              bugs in their expression-building logic.
            </p>
          </div>

          <div className="rounded-lg border bg-muted/30 p-4">
            <h3 className="font-medium mb-2">Documenting existing scheduled tasks</h3>
            <p className="text-sm text-muted-foreground">
              An ops team is documenting their infrastructure. They paste each CRON expression
              into the explainer and copy the human-readable descriptions into their runbooks
              for future reference.
            </p>
          </div>

          <div className="rounded-lg border bg-muted/30 p-4">
            <h3 className="font-medium mb-2">Teaching CRON syntax to new team members</h3>
            <p className="text-sm text-muted-foreground">
              A senior engineer uses the validator as a teaching tool. They show how different
              expressions are parsed, what makes them valid or invalid, and how the English
              translation maps to each field.
            </p>
          </div>

          <div className="rounded-lg border bg-muted/30 p-4">
            <h3 className="font-medium mb-2">Checking expressions before adding to documentation</h3>
            <p className="text-sm text-muted-foreground">
              A technical writer is creating deployment guides that include CRON expressions.
              They validate each expression to ensure the documentation doesn't contain
              typos that would break customer installations.
            </p>
          </div>
        </div>
      </section>

      {/* What to Know Before Using */}
      <section className="space-y-4">
        <h2 className="text-2xl font-semibold">What to Know About CRON Validation</h2>

        <div className="space-y-3 text-muted-foreground">
          <div className="rounded-lg border bg-muted/30 p-4">
            <p className="text-sm">
              <strong className="text-foreground">Syntax validation doesn't guarantee logical correctness.</strong>
              "60 25 32 13 7" is syntactically invalid (out of range), but "0 3 31 2 *" is
              syntactically valid yet never runs (February never has 31 days). The validator
              catches syntax errors, not logic issues.
            </p>
          </div>

          <div className="rounded-lg border bg-muted/30 p-4">
            <p className="text-sm">
              <strong className="text-foreground">Different systems support different extensions.</strong>
              Standard CRON doesn't support "L" for last day or "W" for nearest weekday.
              Some implementations (like Quartz) support these. This validator checks
              standard Unix CRON syntax.
            </p>
          </div>

          <div className="rounded-lg border bg-muted/30 p-4">
            <p className="text-sm">
              <strong className="text-foreground">The 5-field vs 6-field distinction matters.</strong>
              Standard Unix CRON uses 5 fields (no seconds). Some systems like Node.js
              node-cron or Spring use 6 fields with seconds first. Toggle the mode to
              match your target system.
            </p>
          </div>

          <div className="rounded-lg border bg-muted/30 p-4">
            <p className="text-sm">
              <strong className="text-foreground">Field ranges are zero-indexed for hours and days.</strong>
              Hours go from 0 (midnight) to 23 (11 PM), not 1-24. Days of week go from
              0 (Sunday) to 6 (Saturday). This trips up many beginners.
            </p>
          </div>

          <div className="rounded-lg border border-amber-500/30 bg-amber-500/10 p-4">
            <p className="text-sm text-amber-700 dark:text-amber-300">
              <strong>Common gotcha:</strong> If both day-of-month and day-of-week are
              specified (not *), CRON uses OR logic. "0 0 15 * 1" runs on the 15th of
              any month AND every Monday, not just Mondays that fall on the 15th.
            </p>
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section className="space-y-4">
        <h2 className="text-2xl font-semibold">Common Questions</h2>

        <div className="space-y-4">
          <div className="rounded-lg border bg-muted/30 p-4">
            <h3 className="font-medium mb-2">What makes a CRON expression invalid?</h3>
            <p className="text-sm text-muted-foreground">
              Invalid expressions have wrong field count, values outside valid ranges
              (like minute 75), malformed syntax (like "5-"), or invalid characters.
              The validator shows exactly which field failed and why.
            </p>
          </div>

          <div className="rounded-lg border bg-muted/30 p-4">
            <h3 className="font-medium mb-2">How do I read the field breakdown?</h3>
            <p className="text-sm text-muted-foreground">
              Each row shows one field: its name, the value in your expression, the valid
              range, what that field controls, and whether it's valid. Invalid fields
              show in red with specific error details.
            </p>
          </div>

          <div className="rounded-lg border bg-muted/30 p-4">
            <h3 className="font-medium mb-2">What does "*/5" mean in a field?</h3>
            <p className="text-sm text-muted-foreground">
              The slash creates a step interval. "*/5" in minutes means "every 5 minutes"
              (0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55). "10-30/5" means starting
              at 10, every 5th value (10, 15, 20, 25, 30).
            </p>
          </div>

          <div className="rounded-lg border bg-muted/30 p-4">
            <h3 className="font-medium mb-2">Can I use names like "MON" or "JAN"?</h3>
            <p className="text-sm text-muted-foreground">
              Standard Unix CRON doesn't support names—use numbers only. Some extended
              implementations allow "MON" for Monday or "JAN" for January, but for
              maximum compatibility, stick to numeric values.
            </p>
          </div>

          <div className="rounded-lg border bg-muted/30 p-4">
            <h3 className="font-medium mb-2">Why does the explanation sound different from my intent?</h3>
            <p className="text-sm text-muted-foreground">
              The explainer translates exactly what the expression says, not what you
              meant. If you wanted "first Monday of each month" but wrote "0 0 * * 1",
              the explanation correctly says "every Monday" because that's what the
              expression actually specifies.
            </p>
          </div>

          <div className="rounded-lg border bg-muted/30 p-4">
            <h3 className="font-medium mb-2">What's the difference between 5-field and 6-field mode?</h3>
            <p className="text-sm text-muted-foreground">
              5-field mode: minute, hour, day, month, weekday (standard Unix CRON).
              6-field mode: second, minute, hour, day, month, weekday (used by some
              libraries). Use the mode that matches your scheduling system.
            </p>
          </div>

          <div className="rounded-lg border bg-muted/30 p-4">
            <h3 className="font-medium mb-2">How do I validate multiple expressions at once?</h3>
            <p className="text-sm text-muted-foreground">
              This tool validates one expression at a time. For batch validation, consider
              using a script with a CRON parsing library, or validate each expression
              individually as you build your scheduling configuration.
            </p>
          </div>
        </div>
      </section>
    </div>
  )
}
