// Mapping of calculator names to their conversion units and functions
import {
  lengthUnits,
  convertLength,
  weightUnits,
  convertWeight,
  volumeUnits,
  convertVolume,
  temperatureUnits,
  convertTemperature,
  areaUnits,
  convertArea,
  pressureUnits,
  convertPressure,
  energyUnits,
  convertEnergy,
  powerUnits,
  convertPower,
  forceUnits,
  convertForce,
  timeUnits,
  convertTime,
  speedUnits,
  convertSpeed,
  angleUnits,
  convertAngle,
  fuelConsumptionUnits,
  convertFuelConsumption,
  dataStorageUnits,
  convertDataStorage,
  frequencyUnits,
  convertFrequency,
  resolutionUnits,
  convertResolution,
  wavelengthUnits,
  convertWavelength,
  chargeUnits,
  convertCharge,
  currentUnits,
  convertCurrent,
  voltageUnits,
  convertVoltage,
  resistanceUnits,
  convertResistance,
  capacitanceUnits,
  convertCapacitance,
  inductanceUnits,
  convertInductance,
  conductanceUnits,
  convertConductance,
  magneticFluxUnits,
  convertMagneticFlux,
  magneticFluxDensityUnits,
  convertMagneticFluxDensity,
  luminanceUnits,
  convertLuminance,
  illuminanceUnits,
  convertIlluminance,
  luminousIntensityUnits,
  convertLuminousIntensity,
  accelerationUnits,
  convertAcceleration,
  angularVelocityUnits,
  convertAngularVelocity,
  angularAccelerationUnits,
  convertAngularAcceleration,
  densityUnits,
  convertDensity,
  specificVolumeUnits,
  convertSpecificVolume,
  momentOfInertiaUnits,
  convertMomentOfInertia,
  torqueUnits,
  convertTorque,
  specificHeatCapacityUnits,
  convertSpecificHeatCapacity,
  thermalConductivityUnits,
  convertThermalConductivity,
  thermalResistanceUnits,
  convertThermalResistance,
  thermalExpansionUnits,
  convertThermalExpansion,
  temperatureIntervalUnits,
  convertTemperatureInterval,
  heatDensityUnits,
  convertHeatDensity,
  heatFluxDensityUnits,
  convertHeatFluxDensity,
  heatTransferCoefficientUnits,
  convertHeatTransferCoefficient,
  flowUnits,
  convertFlow,
  massFlowUnits,
  convertMassFlow,
  molarFlowUnits,
  convertMolarFlow,
  massFluxDensityUnits,
  convertMassFluxDensity,
  molarConcentrationUnits,
  convertMolarConcentration,
  concentrationUnits,
  convertConcentration,
  dynamicViscosityUnits,
  convertDynamicViscosity,
  kinematicViscosityUnits,
  convertKinematicViscosity,
  surfaceTensionUnits,
  convertSurfaceTension,
  permeabilityUnits,
  convertPermeability,
  electricFieldStrengthUnits,
  convertElectricFieldStrength,
  electricResistivityUnits,
  convertElectricResistivity,
  electricConductivityUnits,
  convertElectricConductivity,
  linearChargeDensityUnits,
  convertLinearChargeDensity,
  surfaceChargeDensityUnits,
  convertSurfaceChargeDensity,
  volumeChargeDensityUnits,
  convertVolumeChargeDensity,
  surfaceCurrentDensityUnits,
  convertSurfaceCurrentDensity,
  magnetomotiveForceUnits,
  convertMagnetomotiveForce,
  magneticFieldStrengthUnits,
  convertMagneticFieldStrength,
  radiationAbsorbedDoseUnits,
  convertRadiationAbsorbedDose,
  radioactivityUnits,
  convertRadioactivity,
  exposureDoseUnits,
  convertExposureDose,
  soundPressureUnits,
  convertSoundPressure,
  windSpeedUnits,
  convertWindSpeed,
  rainfallUnits,
  convertRainfall,
  humidityUnits,
  convertHumidity,
  fabricGsmUnits,
  convertFabricGsm,
  threadCountUnits,
  convertThreadCount,
  heightUnits,
  convertHeight,
  astronomicalDistanceUnits,
  convertAstronomicalDistance,
  type UnitOption,
} from "./conversions";

export interface ConverterConfig {
  units: UnitOption[];
  convertFn: (value: number, from: string, to: string) => number;
  defaultValue?: number;
  defaultFrom?: string;
  defaultTo?: string;
}

export const converterMappings: Record<string, ConverterConfig> = {
  Length: {
    units: lengthUnits,
    convertFn: convertLength,
    defaultValue: 1,
    defaultFrom: "m",
    defaultTo: "ft",
  },
  "Weight and Mass": {
    units: weightUnits,
    convertFn: convertWeight,
    defaultValue: 1,
    defaultFrom: "kg",
    defaultTo: "lb",
  },
  Volume: {
    units: volumeUnits,
    convertFn: convertVolume,
    defaultValue: 1,
    defaultFrom: "L",
    defaultTo: "gal",
  },
  Temperature: {
    units: temperatureUnits,
    convertFn: convertTemperature,
    defaultValue: 0,
    defaultFrom: "C",
    defaultTo: "F",
  },
  Area: {
    units: areaUnits,
    convertFn: convertArea,
    defaultValue: 1,
    defaultFrom: "m²",
    defaultTo: "ft²",
  },
  Pressure: {
    units: pressureUnits,
    convertFn: convertPressure,
    defaultValue: 1,
    defaultFrom: "bar",
    defaultTo: "psi",
  },
  Energy: {
    units: energyUnits,
    convertFn: convertEnergy,
    defaultValue: 1,
    defaultFrom: "kJ",
    defaultTo: "kcal",
  },
  Power: {
    units: powerUnits,
    convertFn: convertPower,
    defaultValue: 1,
    defaultFrom: "kW",
    defaultTo: "hp",
  },
  Force: {
    units: forceUnits,
    convertFn: convertForce,
    defaultValue: 1,
    defaultFrom: "N",
    defaultTo: "lbf",
  },
  Time: {
    units: timeUnits,
    convertFn: convertTime,
    defaultValue: 1,
    defaultFrom: "min",
    defaultTo: "s",
  },
  Speed: {
    units: speedUnits,
    convertFn: convertSpeed,
    defaultValue: 100,
    defaultFrom: "km/h",
    defaultTo: "mph",
  },
  Angle: {
    units: angleUnits,
    convertFn: convertAngle,
    defaultValue: 1,
    defaultFrom: "deg",
    defaultTo: "rad",
  },
  "Fuel Consumption": {
    units: fuelConsumptionUnits,
    convertFn: convertFuelConsumption,
    defaultValue: 30,
    defaultFrom: "mpg",
    defaultTo: "L/100km",
  },
  "Data Storage": {
    units: dataStorageUnits,
    convertFn: convertDataStorage,
    defaultValue: 1,
    defaultFrom: "GB",
    defaultTo: "MB",
  },
  Frequency: {
    units: frequencyUnits,
    convertFn: convertFrequency,
    defaultValue: 1,
    defaultFrom: "MHz",
    defaultTo: "kHz",
  },
  "Digital Image Resolution": {
    units: resolutionUnits,
    convertFn: convertResolution,
    defaultValue: 300,
    defaultFrom: "dpi",
    defaultTo: "dpcm",
  },
  Wavelength: {
    units: wavelengthUnits,
    convertFn: convertWavelength,
    defaultValue: 500,
    defaultFrom: "nm",
    defaultTo: "Hz",
  },
  Charge: {
    units: chargeUnits,
    convertFn: convertCharge,
    defaultValue: 1,
    defaultFrom: "C",
    defaultTo: "mAh",
  },
  Current: {
    units: currentUnits,
    convertFn: convertCurrent,
    defaultValue: 1,
    defaultFrom: "A",
    defaultTo: "mA",
  },
  "Electric Potential": {
    units: voltageUnits,
    convertFn: convertVoltage,
    defaultValue: 1,
    defaultFrom: "V",
    defaultTo: "mV",
  },
  "Electric Resistance": {
    units: resistanceUnits,
    convertFn: convertResistance,
    defaultValue: 1,
    defaultFrom: "Ω",
    defaultTo: "kΩ",
  },
  "Electrostatic Capacitance": {
    units: capacitanceUnits,
    convertFn: convertCapacitance,
    defaultValue: 1,
    defaultFrom: "μF",
    defaultTo: "nF",
  },
  Inductance: {
    units: inductanceUnits,
    convertFn: convertInductance,
    defaultValue: 1,
    defaultFrom: "mH",
    defaultTo: "μH",
  },
  "Electric Conductance": {
    units: conductanceUnits,
    convertFn: convertConductance,
    defaultValue: 1,
    defaultFrom: "S",
    defaultTo: "mS",
  },
  "Magnetic Flux": {
    units: magneticFluxUnits,
    convertFn: convertMagneticFlux,
    defaultValue: 1,
    defaultFrom: "Wb",
    defaultTo: "Mx",
  },
  "Magnetic Flux Density": {
    units: magneticFluxDensityUnits,
    convertFn: convertMagneticFluxDensity,
    defaultValue: 1,
    defaultFrom: "T",
    defaultTo: "G",
  },
  Luminance: {
    units: luminanceUnits,
    convertFn: convertLuminance,
    defaultValue: 100,
    defaultFrom: "cd/m²",
    defaultTo: "fL",
  },
  Illumination: {
    units: illuminanceUnits,
    convertFn: convertIlluminance,
    defaultValue: 100,
    defaultFrom: "lx",
    defaultTo: "fc",
  },
  "Luminous Intensity": {
    units: luminousIntensityUnits,
    convertFn: convertLuminousIntensity,
    defaultValue: 1,
    defaultFrom: "cd",
    defaultTo: "mcd",
  },
  Acceleration: {
    units: accelerationUnits,
    convertFn: convertAcceleration,
    defaultValue: 1,
    defaultFrom: "m/s²",
    defaultTo: "g",
  },
  "Velocity - Angular": {
    units: angularVelocityUnits,
    convertFn: convertAngularVelocity,
    defaultValue: 1,
    defaultFrom: "rad/s",
    defaultTo: "RPM",
  },
  "Acceleration - Angular": {
    units: angularAccelerationUnits,
    convertFn: convertAngularAcceleration,
    defaultValue: 1,
    defaultFrom: "rad/s²",
    defaultTo: "deg/s²",
  },
  Density: {
    units: densityUnits,
    convertFn: convertDensity,
    defaultValue: 1,
    defaultFrom: "g/cm³",
    defaultTo: "kg/m³",
  },
  "Specific Volume": {
    units: specificVolumeUnits,
    convertFn: convertSpecificVolume,
    defaultValue: 1,
    defaultFrom: "m³/kg",
    defaultTo: "ft³/lb",
  },
  "Moment of Inertia": {
    units: momentOfInertiaUnits,
    convertFn: convertMomentOfInertia,
    defaultValue: 1,
    defaultFrom: "kg·m²",
    defaultTo: "lb·ft²",
  },
  Torque: {
    units: torqueUnits,
    convertFn: convertTorque,
    defaultValue: 1,
    defaultFrom: "N·m",
    defaultTo: "lbf·ft",
  },
  "Moment of Force": {
    units: torqueUnits,
    convertFn: convertTorque,
    defaultValue: 1,
    defaultFrom: "N·m",
    defaultTo: "lbf·ft",
  },
  "Specific Heat Capacity": {
    units: specificHeatCapacityUnits,
    convertFn: convertSpecificHeatCapacity,
    defaultValue: 1,
    defaultFrom: "J/(kg·K)",
    defaultTo: "cal/(g·°C)",
  },
  "Thermal Conductivity": {
    units: thermalConductivityUnits,
    convertFn: convertThermalConductivity,
    defaultValue: 1,
    defaultFrom: "W/(m·K)",
    defaultTo: "BTU/(h·ft·°F)",
  },
  "Thermal Resistance": {
    units: thermalResistanceUnits,
    convertFn: convertThermalResistance,
    defaultValue: 1,
    defaultFrom: "K/W",
    defaultTo: "°F·h/BTU",
  },
  "Thermal Expansion": {
    units: thermalExpansionUnits,
    convertFn: convertThermalExpansion,
    defaultValue: 1,
    defaultFrom: "1/K",
    defaultTo: "1/°F",
  },
  "Temperature Interval": {
    units: temperatureIntervalUnits,
    convertFn: convertTemperatureInterval,
    defaultValue: 1,
    defaultFrom: "K",
    defaultTo: "°F",
  },
  "Heat Density": {
    units: heatDensityUnits,
    convertFn: convertHeatDensity,
    defaultValue: 1000,
    defaultFrom: "J/m³",
    defaultTo: "BTU/ft³",
  },
  "Heat Flux Density": {
    units: heatFluxDensityUnits,
    convertFn: convertHeatFluxDensity,
    defaultValue: 1,
    defaultFrom: "W/m²",
    defaultTo: "BTU/(h·ft²)",
  },
  "Heat Transfer Coefficient": {
    units: heatTransferCoefficientUnits,
    convertFn: convertHeatTransferCoefficient,
    defaultValue: 1,
    defaultFrom: "W/(m²·K)",
    defaultTo: "BTU/(h·ft²·°F)",
  },
  Flow: {
    units: flowUnits,
    convertFn: convertFlow,
    defaultValue: 1,
    defaultFrom: "L/min",
    defaultTo: "gal/min",
  },
  "Flow - Mass": {
    units: massFlowUnits,
    convertFn: convertMassFlow,
    defaultValue: 1,
    defaultFrom: "kg/s",
    defaultTo: "lb/min",
  },
  "Flow - Molar": {
    units: molarFlowUnits,
    convertFn: convertMolarFlow,
    defaultValue: 1,
    defaultFrom: "mol/s",
    defaultTo: "kmol/h",
  },
  "Mass Flux Density": {
    units: massFluxDensityUnits,
    convertFn: convertMassFluxDensity,
    defaultValue: 1,
    defaultFrom: "kg/(m²·s)",
    defaultTo: "lb/(ft²·s)",
  },
  "Concentration - Molar": {
    units: molarConcentrationUnits,
    convertFn: convertMolarConcentration,
    defaultValue: 1,
    defaultFrom: "mol/L",
    defaultTo: "mmol/L",
  },
  "Concentration - Solution": {
    units: concentrationUnits,
    convertFn: convertConcentration,
    defaultValue: 100,
    defaultFrom: "ppm",
    defaultTo: "mg/L",
  },
  "Viscosity - Dynamic": {
    units: dynamicViscosityUnits,
    convertFn: convertDynamicViscosity,
    defaultValue: 1,
    defaultFrom: "cP",
    defaultTo: "Pa·s",
  },
  "Viscosity - Kinematic": {
    units: kinematicViscosityUnits,
    convertFn: convertKinematicViscosity,
    defaultValue: 1,
    defaultFrom: "cSt",
    defaultTo: "St",
  },
  "Surface Tension": {
    units: surfaceTensionUnits,
    convertFn: convertSurfaceTension,
    defaultValue: 1,
    defaultFrom: "N/m",
    defaultTo: "dyn/cm",
  },
  Permeability: {
    units: permeabilityUnits,
    convertFn: convertPermeability,
    defaultValue: 1,
    defaultFrom: "D",
    defaultTo: "mD",
  },
  "Electric Field Strength": {
    units: electricFieldStrengthUnits,
    convertFn: convertElectricFieldStrength,
    defaultValue: 1,
    defaultFrom: "V/m",
    defaultTo: "kV/m",
  },
  "Electric Resistivity": {
    units: electricResistivityUnits,
    convertFn: convertElectricResistivity,
    defaultValue: 1,
    defaultFrom: "Ω·m",
    defaultTo: "Ω·cm",
  },
  "Electric Conductivity": {
    units: electricConductivityUnits,
    convertFn: convertElectricConductivity,
    defaultValue: 1,
    defaultFrom: "S/m",
    defaultTo: "mS/cm",
  },
  "Linear Charge Density": {
    units: linearChargeDensityUnits,
    convertFn: convertLinearChargeDensity,
    defaultValue: 1,
    defaultFrom: "C/m",
    defaultTo: "μC/cm",
  },
  "Surface Charge Density": {
    units: surfaceChargeDensityUnits,
    convertFn: convertSurfaceChargeDensity,
    defaultValue: 1,
    defaultFrom: "C/m²",
    defaultTo: "mC/cm²",
  },
  "Volume Charge Density": {
    units: volumeChargeDensityUnits,
    convertFn: convertVolumeChargeDensity,
    defaultValue: 1,
    defaultFrom: "C/m³",
    defaultTo: "μC/mm³",
  },
  "Linear Current Density": {
    units: linearChargeDensityUnits,
    convertFn: convertLinearChargeDensity,
    defaultValue: 1,
    defaultFrom: "A/m",
    defaultTo: "mA/cm",
  },
  "Surface Current Density": {
    units: surfaceCurrentDensityUnits,
    convertFn: convertSurfaceCurrentDensity,
    defaultValue: 1,
    defaultFrom: "A/m²",
    defaultTo: "mA/cm²",
  },
  "Magnetomotive Force": {
    units: magnetomotiveForceUnits,
    convertFn: convertMagnetomotiveForce,
    defaultValue: 1,
    defaultFrom: "A·t",
    defaultTo: "Gi",
  },
  "Magnetic Field Strength": {
    units: magneticFieldStrengthUnits,
    convertFn: convertMagneticFieldStrength,
    defaultValue: 1,
    defaultFrom: "A/m",
    defaultTo: "Oe",
  },
  "Radiation Dose": {
    units: radiationAbsorbedDoseUnits,
    convertFn: convertRadiationAbsorbedDose,
    defaultValue: 1,
    defaultFrom: "Gy",
    defaultTo: "rad",
  },
  Radioactivity: {
    units: radioactivityUnits,
    convertFn: convertRadioactivity,
    defaultValue: 1,
    defaultFrom: "MBq",
    defaultTo: "mCi",
  },
  "Exposure Dose Converter": {
    units: exposureDoseUnits,
    convertFn: convertExposureDose,
    defaultValue: 1,
    defaultFrom: "R",
    defaultTo: "C/kg",
  },
  "Sound Pressure (Pa to dB)": {
    units: soundPressureUnits,
    convertFn: convertSoundPressure,
    defaultValue: 1,
    defaultFrom: "Pa",
    defaultTo: "dB",
  },
  "Wind Speed Converter": {
    units: windSpeedUnits,
    convertFn: convertWindSpeed,
    defaultValue: 10,
    defaultFrom: "m/s",
    defaultTo: "km/h",
  },
  "Rainfall Converter": {
    units: rainfallUnits,
    convertFn: convertRainfall,
    defaultValue: 1,
    defaultFrom: "mm",
    defaultTo: "in",
  },
  "Humidity Ratio Converter": {
    units: humidityUnits,
    convertFn: convertHumidity,
    defaultValue: 50,
    defaultFrom: "RH%",
    defaultTo: "AH g/m³",
  },
  "Fabric GSM Converter": {
    units: fabricGsmUnits,
    convertFn: convertFabricGsm,
    defaultValue: 100,
    defaultFrom: "gsm",
    defaultTo: "oz/yd²",
  },
  "Thread Count Converter": {
    units: threadCountUnits,
    convertFn: convertThreadCount,
    defaultValue: 100,
    defaultFrom: "TC",
    defaultTo: "TC/cm²",
  },
  "Height Converter": {
    units: heightUnits,
    convertFn: convertHeight,
    defaultValue: 170,
    defaultFrom: "cm",
    defaultTo: "ft",
  },
  "Light Years to Parsecs": {
    units: astronomicalDistanceUnits,
    convertFn: convertAstronomicalDistance,
    defaultValue: 1,
    defaultFrom: "ly",
    defaultTo: "pc",
  },
  "Astronomical Unit Converter": {
    units: astronomicalDistanceUnits,
    convertFn: convertAstronomicalDistance,
    defaultValue: 1,
    defaultFrom: "AU",
    defaultTo: "km",
  },
  // Volume - Dry
  "Volume - Dry": {
    units: volumeUnits,
    convertFn: convertVolume,
    defaultValue: 1,
    defaultFrom: "gal",
    defaultTo: "L",
  },
  // Fuel Efficiency - Mass
  "Fuel Efficiency - Mass": {
    units: fuelConsumptionUnits,
    convertFn: convertFuelConsumption,
    defaultValue: 30,
    defaultFrom: "mpg",
    defaultTo: "km/L",
  },
  // Fuel Efficiency - Volume
  "Fuel Efficiency - Volume": {
    units: fuelConsumptionUnits,
    convertFn: convertFuelConsumption,
    defaultValue: 30,
    defaultFrom: "mpg",
    defaultTo: "L/100km",
  },
  // Rebar Weight Calculator
  "Rebar Weight Calculator": {
    units: weightUnits,
    convertFn: convertWeight,
    defaultValue: 1,
    defaultFrom: "kg",
    defaultTo: "lb",
  },
  // Concrete Volume Converter
  "Concrete Volume Converter": {
    units: volumeUnits,
    convertFn: convertVolume,
    defaultValue: 1,
    defaultFrom: "m³",
    defaultTo: "ft³",
  },
  // Concrete Mix Ratio Converter
  "Concrete Mix Ratio Converter": {
    units: volumeUnits,
    convertFn: convertVolume,
    defaultValue: 1,
    defaultFrom: "m³",
    defaultTo: "ft³",
  },
  // Brick Calculator
  "Brick Calculator": {
    units: lengthUnits,
    convertFn: convertLength,
    defaultValue: 1,
    defaultFrom: "m",
    defaultTo: "ft",
  },
  // Tile Calculator
  "Tile Calculator": {
    units: areaUnits,
    convertFn: convertArea,
    defaultValue: 1,
    defaultFrom: "m²",
    defaultTo: "ft²",
  },
  // Cement-Sand-Aggregate Converter
  "Cement-Sand-Aggregate Converter": {
    units: weightUnits,
    convertFn: convertWeight,
    defaultValue: 1,
    defaultFrom: "kg",
    defaultTo: "lb",
  },
  // Lumber Board Feet Converter
  "Lumber Board Feet Converter": {
    units: lengthUnits,
    convertFn: convertLength,
    defaultValue: 1,
    defaultFrom: "ft",
    defaultTo: "m",
  },
  // Floor Area Converter
  "Floor Area Converter": {
    units: areaUnits,
    convertFn: convertArea,
    defaultValue: 1,
    defaultFrom: "m²",
    defaultTo: "ft²",
  },
  // Roofing Sheet Coverage Converter
  "Roofing Sheet Coverage Converter": {
    units: areaUnits,
    convertFn: convertArea,
    defaultValue: 1,
    defaultFrom: "m²",
    defaultTo: "ft²",
  },
  // Cups to Grams
  "Cups to Grams": {
    units: weightUnits,
    convertFn: convertWeight,
    defaultValue: 1,
    defaultFrom: "cup",
    defaultTo: "g",
  },
  // Cups to ml
  "Cups to ml": {
    units: volumeUnits,
    convertFn: convertVolume,
    defaultValue: 1,
    defaultFrom: "cup",
    defaultTo: "mL",
  },
  // Oven Temperature Converter
  "Oven Temperature Converter": {
    units: temperatureUnits,
    convertFn: convertTemperature,
    defaultValue: 180,
    defaultFrom: "C",
    defaultTo: "F",
  },
  // Baking Pan Size Converter
  "Baking Pan Size Converter": {
    units: volumeUnits,
    convertFn: convertVolume,
    defaultValue: 1,
    defaultFrom: "L",
    defaultTo: "cup",
  },
  // Ingredient Density Converter
  "Ingredient Density Converter": {
    units: densityUnits,
    convertFn: convertDensity,
    defaultValue: 1,
    defaultFrom: "g/cm³",
    defaultTo: "kg/m³",
  },
  // Sourdough Hydration Converter
  "Sourdough Hydration Converter": {
    units: weightUnits,
    convertFn: convertWeight,
    defaultValue: 100,
    defaultFrom: "g",
    defaultTo: "g",
  },
  // Image DPI Converter
  "Image DPI Converter": {
    units: resolutionUnits,
    convertFn: convertResolution,
    defaultValue: 300,
    defaultFrom: "dpi",
    defaultTo: "dpcm",
  },
  // Video Frame Rate Converter
  "Video Frame Rate Converter": {
    units: frequencyUnits,
    convertFn: convertFrequency,
    defaultValue: 30,
    defaultFrom: "Hz",
    defaultTo: "RPM",
  },
  // Audio Bitrate Converter
  "Audio Bitrate Converter": {
    units: frequencyUnits,
    convertFn: convertFrequency,
    defaultValue: 128,
    defaultFrom: "kHz",
    defaultTo: "Hz",
  },
  // Unix Timestamp Converter
  "Unix Timestamp Converter": {
    units: timeUnits,
    convertFn: convertTime,
    defaultValue: 1,
    defaultFrom: "s",
    defaultTo: "d",
  },
  // Time Duration Calculator
  "Time Duration Calculator": {
    units: timeUnits,
    convertFn: convertTime,
    defaultValue: 1,
    defaultFrom: "h",
    defaultTo: "min",
  },
  // Age Calculator
  "Age Calculator": {
    units: timeUnits,
    convertFn: convertTime,
    defaultValue: 1,
    defaultFrom: "y",
    defaultTo: "d",
  },
  // Date Difference Calculator
  "Date Difference Calculator": {
    units: timeUnits,
    convertFn: convertTime,
    defaultValue: 1,
    defaultFrom: "d",
    defaultTo: "wk",
  },
  // Apparent Magnitude Converter
  "Apparent Magnitude Converter": {
    units: [
      { value: "mag", label: "Magnitude" },
      { value: "lum", label: "Luminosity" },
    ],
    convertFn: (v: number) => v,
    defaultValue: 1,
    defaultFrom: "mag",
    defaultTo: "lum",
  },
  // Planet Weight Converter
  "Planet Weight Converter": {
    units: weightUnits,
    convertFn: convertWeight,
    defaultValue: 70,
    defaultFrom: "kg",
    defaultTo: "kg",
  },
  // Frequency to Musical Note Converter
  "Frequency to Musical Note Converter": {
    units: frequencyUnits,
    convertFn: convertFrequency,
    defaultValue: 440,
    defaultFrom: "Hz",
    defaultTo: "Hz",
  },
  // Dew Point Calculator
  "Dew Point Calculator": {
    units: temperatureUnits,
    convertFn: convertTemperature,
    defaultValue: 20,
    defaultFrom: "C",
    defaultTo: "F",
  },
  // Clothing Size Converter
  "Clothing Size Converter": {
    units: [
      { value: "US", label: "US" },
      { value: "UK", label: "UK" },
      { value: "EU", label: "EU" },
    ],
    convertFn: (v: number) => v,
    defaultValue: 1,
    defaultFrom: "US",
    defaultTo: "EU",
  },
  // BMI Calculator
  "BMI Calculator": {
    units: weightUnits,
    convertFn: convertWeight,
    defaultValue: 70,
    defaultFrom: "kg",
    defaultTo: "kg",
  },
  // Calorie Burn Rate Converter
  "Calorie Burn Rate Converter": {
    units: energyUnits,
    convertFn: convertEnergy,
    defaultValue: 100,
    defaultFrom: "kcal",
    defaultTo: "kJ",
  },
  // Running Pace to Speed Converter
  "Running Pace to Speed Converter": {
    units: speedUnits,
    convertFn: convertSpeed,
    defaultValue: 10,
    defaultFrom: "km/h",
    defaultTo: "mph",
  },
  // Shoe Size Converter
  "Shoe Size Converter": {
    units: lengthUnits,
    convertFn: convertLength,
    defaultValue: 1,
    defaultFrom: "cm",
    defaultTo: "in",
  },
  // Ring Size Converter
  "Ring Size Converter": {
    units: lengthUnits,
    convertFn: convertLength,
    defaultValue: 1,
    defaultFrom: "cm",
    defaultTo: "in",
  },
  // Horsepower to Animals Converter
  "Horsepower to Animals Converter": {
    units: powerUnits,
    convertFn: convertPower,
    defaultValue: 1,
    defaultFrom: "hp",
    defaultTo: "W",
  },
};

// Get slug from calculator name
export function getSlugFromName(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}
