import type { Metadata } from "next";
import UuidEntropyCheckerSeo from "@/components/seo-content/uuid-tools/uuid-entropy-checker";

import ToolLinkCards from "@/components/utils/ToolLinkCards";
import { UuidEntropyChecker } from "@/components/uuid-tools/uuid-entropy-checker";

export const metadata: Metadata = {
  title: `UUID Randomness Checker | Analyze UUID v4 Entropy`,
  description: `Analyze the randomness of UUID v4 identifiers. Check for patterns and biases to ensure your UUIDs are cryptographically strong and properly random.`,
  alternates: {
    canonical: `/uuid-tools/uuid-entropy-checker`,
  },
};

const tools = [
  {
    name: `UUID Generator`,
    description: `Free UUID Generator`,
    href: `/uuid-tools/uuid-generator`,
  },
  {
    name: `UUID Decoder`,
    description: `UUID Decoder & Analyzer`,
    href: `/uuid-tools/uuid-decoder`,
  },
  {
    name: `UUID Validator`,
    description: `UUID Validator & Checker`,
    href: `/uuid-tools/uuid-validator`,
  },
  {
    name: `UUID Version Converter`,
    description: `UUID Version Converter (v3, v5)`,
    href: `/uuid-tools/uuid-version-converter`,
  },
  {
    name: `Bulk UUID Generator`,
    description: `Bulk UUID Generator for Mass Production`,
    href: `/uuid-tools/bulk-uuid-generator`,
  },
  {
    name: `ASCII to Hex Converter`,
    description: `ASCII to Hex Converter: Text to Hexadecimal Translator`,
    href: `/ascii-tools/ascii-to-hex-converter`,
  },
  {
    name: `Barcode Generator`,
    description: `Free Barcode Generator`,
    href: `/barcode-tools/barcode-generator`,
  },
  {
    name: `Binary to Text Converter`,
    description: `Binary to Text Converter`,
    href: `/binary-tools/binary-to-text-converter`,
  },
  {
    name: `Free Printable Calendar Maker`,
    description: `Create & Print Your Custom Calendar`,
    href: `/calendar-tools/printable-calendar-maker`,
  },
  {
    name: `Pie Chart Maker`,
    description: `Free Pie Chart Maker Online`,
    href: `/chart-tools/pie-chart-maker`,
  },
];

export default function UuidEntropyCheckerPage() {
  return (
    <div className="flex flex-col gap-y-4">
      <header className="max-w-3xl">
        <h1 className="text-3xl font-bold mb-3">UUID Randomness & Entropy Analyzer</h1>
        <p className="text-muted-foreground">Check the quality of a UUID v4's randomness. This tool analyzes the hex digits for patterns and biases, providing a simple assessment to help identify potentially weak identifiers generated by flawed random number generators.</p>
      </header>
      {<UuidEntropyChecker />}
      <div className="mt-16">
        <UuidEntropyCheckerSeo />
      </div>
      <div className="mt-16 max-w-6xl">
        <h2 className="text-2xl font-semibold mb-6 text-center">Other Free Tools</h2>
        <ToolLinkCards tools={tools} />
      </div>
    </div>
  );
}
