const urls = [
  // "https://1000freetools.com/calculators/royalty-calculator",
  // "https://1000freetools.com/calculators/rpm-calculator",
  // "https://1000freetools.com/calculators/rsa-key-strength-calculator",
  // "https://1000freetools.com/calculators/rsu-vesting-calculator",
  // "https://1000freetools.com/calculators/rule-of-72-calculator",
  // "https://1000freetools.com/calculators/running-pace-calculator",
  // "https://1000freetools.com/calculators/running-split-calculator",
  // "https://1000freetools.com/calculators/saas-churn-rate-calculator",
  // "https://1000freetools.com/calculators/saas-mrr-arr-calculator",
  // "https://1000freetools.com/calculators/safety-factor-calculator",
  // "https://1000freetools.com/calculators/salary-to-hourly-calculator",
  // "https://1000freetools.com/calculators/sand-quantity-calculator",
  // "https://1000freetools.com/calculators/savings-goal-calculator",
  // "https://1000freetools.com/calculators/savings-vs-investment-comparison",
  // "https://1000freetools.com/calculators/scaffold-board-calculator",
  // "https://1000freetools.com/calculators/scale-finder",
  // "https://1000freetools.com/calculators/scientific-notation-calculator",
  // "https://1000freetools.com/calculators/screen-brightness-battery-calculator",
  // "https://1000freetools.com/calculators/screen-time-allowance-calculator",
  // "https://1000freetools.com/calculators/screen-time-calculator",
  // "https://1000freetools.com/calculators/screw-thread-pitch-calculator",
  // "https://1000freetools.com/calculators/sector-area-calculator",
  // "https://1000freetools.com/calculators/seed-rate-calculator",
  // "https://1000freetools.com/calculators/series-parallel-capacitor-calculator",
  // "https://1000freetools.com/calculators/series-parallel-resistor-calculator",
  // "https://1000freetools.com/calculators/shaft-torque-calculator",
  // "https://1000freetools.com/calculators/shoe-size-converter",
  // "https://1000freetools.com/calculators/shutter-speed-calculator",
  // "https://1000freetools.com/calculators/signal-to-noise-ratio-calculator",
  // "https://1000freetools.com/calculators/simple-interest-calculator",
  // "https://1000freetools.com/calculators/simplify-fraction-calculator",
  // "https://1000freetools.com/calculators/sip-calculator",
  // "https://1000freetools.com/calculators/sip-step-up-calculator",
  // "https://1000freetools.com/calculators/sleep-cycle-calculator",
  // "https://1000freetools.com/calculators/sleep-debt-calculator",
  // "https://1000freetools.com/calculators/sleep-wake-efficiency-calculator",
  // "https://1000freetools.com/calculators/slope-calculator",
  // "https://1000freetools.com/calculators/snells-law-calculator",
  // "https://1000freetools.com/calculators/soil-ph-adjustment-calculator",
  // "https://1000freetools.com/calculators/solar-irradiance-calculator",
  // "https://1000freetools.com/calculators/solar-panel-requirement-calculator",
  // "https://1000freetools.com/calculators/solubility-product-ksp-calculator",
  // "https://1000freetools.com/calculators/sound-speed-calculator",
  // "https://1000freetools.com/calculators/speed-calculator",
  // "https://1000freetools.com/calculators/speed-to-pace-converter",
  // "https://1000freetools.com/calculators/spring-force-hookes-law-calculator",
  // "https://1000freetools.com/calculators/square-area-calculator",
  // "https://1000freetools.com/calculators/staircase-rise-run-calculator",
  // "https://1000freetools.com/calculators/standard-deviation-calculator",
  // "https://1000freetools.com/calculators/startup-equity-calculator",
  // "https://1000freetools.com/calculators/steel-weight-calculator",
  // "https://1000freetools.com/calculators/step-down-sip-calculator",
  // "https://1000freetools.com/calculators/steps-to-calories-calculator",
  // "https://1000freetools.com/calculators/stock-cagr-calculator",
  // "https://1000freetools.com/calculators/stock-split-calculator",
  // "https://1000freetools.com/calculators/stoichiometry-calculator",
  // "https://1000freetools.com/calculators/strength-training-pr-estimator",
  // "https://1000freetools.com/calculators/stress-strain-calculator",
  // "https://1000freetools.com/calculators/study-hour-efficiency-calculator",
  // "https://1000freetools.com/calculators/study-hour-planner",
  // "https://1000freetools.com/calculators/subscription-pricing-calculator",
  // "https://1000freetools.com/calculators/subscription-profit-calculator",
  // "https://1000freetools.com/calculators/subtraction-calculator",
  // "https://1000freetools.com/calculators/swimming-calorie-calculator",
  // "https://1000freetools.com/calculators/swimming-lap-pace-calculator",
  // "https://1000freetools.com/calculators/swp-calculator",
  // "https://1000freetools.com/calculators/tdee-calculator",
  // "https://1000freetools.com/calculators/tea-brewing-strength-calculator",
  // "https://1000freetools.com/calculators/telescope-magnification-calculator",
  // "https://1000freetools.com/calculators/tempo-to-delay-time-converter",
  // "https://1000freetools.com/calculators/tennis-win-probability-calculator",
  // "https://1000freetools.com/calculators/thermal-expansion-calculator",
  // "https://1000freetools.com/calculators/tile-calculator",
  // "https://1000freetools.com/calculators/time-duration-calculator",
  // "https://1000freetools.com/calculators/tire-pressure-adjustment-calculator",
  // "https://1000freetools.com/calculators/titration-calculator",
  // "https://1000freetools.com/calculators/toddler-growth-chart-calculator",
  // "https://1000freetools.com/calculators/torque-calculator",
  // "https://1000freetools.com/calculators/torque-to-power-converter",
  // "https://1000freetools.com/calculators/trail-difficulty-estimator",
  // "https://1000freetools.com/calculators/trapezoid-area-calculator",
  // "https://1000freetools.com/calculators/triangle-area-calculator",
  // "https://1000freetools.com/calculators/trip-cost-estimator",
  // "https://1000freetools.com/calculators/tuning-frequency-converter",
  // "https://1000freetools.com/calculators/typography-scale-calculator",
  // "https://1000freetools.com/calculators/unit-price-calculator",
  // "https://1000freetools.com/calculators/unix-timestamp-converter",
  // "https://1000freetools.com/calculators/ups-generator-runtime-calculator",
  // "https://1000freetools.com/calculators/ups-load-calculator",
  // "https://1000freetools.com/calculators/valuation-cap-calculator",
  // "https://1000freetools.com/calculators/vapor-pressure-calculator",
  // "https://1000freetools.com/calculators/variance-calculator",
  // "https://1000freetools.com/calculators/vehicle-depreciation-calculator",
  // "https://1000freetools.com/calculators/vehicle-turning-radius-calculator",
  // "https://1000freetools.com/calculators/velocity-calculator",
  // "https://1000freetools.com/calculators/ventilation-rate-calculator",
  // "https://1000freetools.com/calculators/vo2-max-calculator",
  // "https://1000freetools.com/calculators/voltage-calculator",
  // "https://1000freetools.com/calculators/volume-of-cone-calculator",
  // "https://1000freetools.com/calculators/volume-of-cube-calculator",
  // "https://1000freetools.com/calculators/volume-of-cuboid-calculator",
  // "https://1000freetools.com/calculators/volume-of-cylinder-calculator",
  // "https://1000freetools.com/calculators/volume-of-pyramid-calculator",
  // "https://1000freetools.com/calculators/volume-of-sphere-calculator",
  // "https://1000freetools.com/calculators/volumetric-weight-calculator",
  // "https://1000freetools.com/calculators/wacc-calculator",
  // "https://1000freetools.com/calculators/waist-to-height-ratio-calculator",
  // "https://1000freetools.com/calculators/waist-to-hip-ratio-calculator",
  // "https://1000freetools.com/calculators/walking-calorie-calculator",
  // "https://1000freetools.com/calculators/wallpaper-calculator",
  // "https://1000freetools.com/calculators/warehouse-storage-volume-calculator",
  // "https://1000freetools.com/calculators/warm-up-calculator",
  // "https://1000freetools.com/calculators/water-flow-rate-calculator",
  // "https://1000freetools.com/calculators/water-intake-activity-calculator",
  // "https://1000freetools.com/calculators/water-requirement-calculator",
  // "https://1000freetools.com/calculators/water-tank-volume-calculator",
  // "https://1000freetools.com/calculators/wavelength-calculator",
  // "https://1000freetools.com/calculators/wbc-count-calculator",
  // "https://1000freetools.com/calculators/wealth-growth-projection-calculator",
  // "https://1000freetools.com/calculators/week-number-calculator",
  // "https://1000freetools.com/calculators/weight-distribution-calculator",
  // "https://1000freetools.com/calculators/weight-loss-time-calculator",
  // "https://1000freetools.com/calculators/weighted-average-calculator",
  // "https://1000freetools.com/calculators/welding-strength-calculator",
  // "https://1000freetools.com/calculators/win-rate-estimator",
  // "https://1000freetools.com/calculators/wind-chill-calculator",
  // "https://1000freetools.com/calculators/window-area-calculator",
  // "https://1000freetools.com/calculators/wine-abv-calculator",
  // "https://1000freetools.com/calculators/wire-gauge-calculator",
  // "https://1000freetools.com/calculators/wood-board-feet-calculator",
  // "https://1000freetools.com/calculators/work-calculator",
  // "https://1000freetools.com/calculators/work-hours-calculator",
  // "https://1000freetools.com/calculators/working-capital-calculator",
  // "https://1000freetools.com/calculators/workout-max-reps-estimator",
  // "https://1000freetools.com/calculators/workout-rest-timer",
  // "https://1000freetools.com/calculators/workout-volume-calculator",
  // "https://1000freetools.com/calculators/xp-progression-calculator",
  // "https://1000freetools.com/calculators/yeast-conversion-calculator",
  // "https://1000freetools.com/calculators/yield-to-maturity-calculator",
  // "https://1000freetools.com/calculators/z-score-calculator",
  // "https://1000freetools.com/calculators/zodiac-sign-calculator",
  // "https://1000freetools.com/color-tools/advanced-color-picker",
  // "https://1000freetools.com/color-tools/color-harmony-generator",
  // "https://1000freetools.com/color-tools/color-history-tool",
  // "https://1000freetools.com/color-tools/color-palette-generator",
  // "https://1000freetools.com/color-tools/color-palettes",
  // "https://1000freetools.com/color-tools/color-picker",
  // "https://1000freetools.com/color-tools/color-scale-generator",
  // "https://1000freetools.com/color-tools/color-temperature-to-rgb",
  // "https://1000freetools.com/color-tools/color-wheel",
  // "https://1000freetools.com/color-tools/complementary-color-finder",
  // "https://1000freetools.com/color-tools/contrast-checker",
  // "https://1000freetools.com/color-tools/css-color-name-converter",
  // "https://1000freetools.com/color-tools/css-gradient-generator",
  // "https://1000freetools.com/color-tools/css-variables-generator",
  // "https://1000freetools.com/color-tools/custom-color-palette-generator",
  // "https://1000freetools.com/color-tools/dark-light-mode-preview",
  // "https://1000freetools.com/color-tools/dominant-color-finder",
  // "https://1000freetools.com/color-tools/duotone-palette-generator",
  // "https://1000freetools.com/color-tools/extract-colors-from-image",
  // "https://1000freetools.com/color-tools/favorite-colors-manager",
  // "https://1000freetools.com/color-tools/gradient-palette-generator",
  // "https://1000freetools.com/color-tools/gradient-step-generator",
  // "https://1000freetools.com/color-tools/hex-to-cmyk-converter",
  // "https://1000freetools.com/color-tools/hex-to-hsl-converter",
  // "https://1000freetools.com/color-tools/hex-to-rgb-converter",
  // "https://1000freetools.com/color-tools/hsl-to-hex-converter",
  // "https://1000freetools.com/color-tools/hsl-to-hsv-converter",
  // "https://1000freetools.com/color-tools/monochrome-palette-generator",
  // "https://1000freetools.com/color-tools",
  // "https://1000freetools.com/color-tools/palette-comparison-tool",
  // "https://1000freetools.com/color-tools/palette-contrast-viewer",
  // "https://1000freetools.com/color-tools/palette-duplicate-finder",
  // "https://1000freetools.com/color-tools/palette-export-tool",
  // "https://1000freetools.com/color-tools/palette-merger",
  // "https://1000freetools.com/color-tools/palette-sorter",
  // "https://1000freetools.com/color-tools/pastel-palette-generator",
  // "https://1000freetools.com/color-tools/random-color-palette-generator",
  // "https://1000freetools.com/color-tools/rgb-to-cmyk-converter",
  // "https://1000freetools.com/color-tools/rgb-to-hex-converter",
  // "https://1000freetools.com/color-tools/rgb-to-hsl-converter",
  // "https://1000freetools.com/color-tools/shade-tint-tone-generator",
  // "https://1000freetools.com/color-tools/text-color-suggestion-tool",
  // "https://1000freetools.com/color-tools/warm-or-cool-color-detector",
  // "https://1000freetools.com/color-tools/web-safe-color-picker",
  // "https://1000freetools.com/contact",
  // "https://1000freetools.com/css-tools/animation-generator",
  // "https://1000freetools.com/css-tools/aspect-ratio-calculator",
  // "https://1000freetools.com/css-tools/background-noise-generator",
  // "https://1000freetools.com/css-tools/border-radius-generator",
  // "https://1000freetools.com/css-tools/box-shadow-generator",
  // "https://1000freetools.com/css-tools/clip-path-maker",
  // "https://1000freetools.com/css-tools/color-contrast-checker",
  // "https://1000freetools.com/css-tools/color-converter",
  // "https://1000freetools.com/css-tools/color-palette-generator",
  // "https://1000freetools.com/css-tools/css-button-generator",
  // "https://1000freetools.com/css-tools/css-calc-builder",
  // "https://1000freetools.com/css-tools/css-counter-generator",
  // "https://1000freetools.com/css-tools/css-filter-generator",
  // "https://1000freetools.com/css-tools/css-font-face-generator",
  "https://1000freetools.com/css-tools/css-grid-generator",
  "https://1000freetools.com/css-tools/css-loader-generator",
  "https://1000freetools.com/css-tools/css-mesh-gradient-generator",
  "https://1000freetools.com/css-tools/css-minifier",
  "https://1000freetools.com/css-tools/css-pattern-generator",
  "https://1000freetools.com/css-tools/css-playground",
  "https://1000freetools.com/css-tools/css-shape-generator",
  "https://1000freetools.com/css-tools/css-spacing-scale-generator",
  "https://1000freetools.com/css-tools/css-specificity-calculator",
  "https://1000freetools.com/css-tools/css-transition-previewer",
  "https://1000freetools.com/css-tools/css-variable-extractor",
  "https://1000freetools.com/css-tools/cubic-bezier-editor",
  "https://1000freetools.com/css-tools/dark-mode-css-generator",
  "https://1000freetools.com/css-tools/flexbox-playground",
  "https://1000freetools.com/css-tools/fluid-space-calculator",
  "https://1000freetools.com/css-tools/fluid-typography-calculator",
  "https://1000freetools.com/css-tools/glassmorphism-generator",
  "https://1000freetools.com/css-tools/google-fonts-pairing-tool",
  "https://1000freetools.com/css-tools/gradient-generator",
  "https://1000freetools.com/css-tools/letter-spacing-line-height-visualizer",
  "https://1000freetools.com/css-tools/media-query-builder",
  "https://1000freetools.com/css-tools/neumorphism-generator",
  "https://1000freetools.com/css-tools",
  "https://1000freetools.com/css-tools/playground",
  "https://1000freetools.com/css-tools/print-css-helper",
  "https://1000freetools.com/css-tools/px-rem-converter",
  "https://1000freetools.com/css-tools/scroll-snap-builder",
  "https://1000freetools.com/css-tools/text-shadow-generator",
  "https://1000freetools.com/css-tools/tint-shade-generator",
  "https://1000freetools.com/css-tools/viewport-unit-converter",
  "https://1000freetools.com/csv-tools/csv-viewer",
  "https://1000freetools.com/csv-tools",
  "https://1000freetools.com/design-tools/favicon-generator",
  "https://1000freetools.com/design-tools",
  "https://1000freetools.com/developer-tools/js-online-compiler",
  "https://1000freetools.com/developer-tools/mock-data-generator",
  "https://1000freetools.com/developer-tools",
  "https://1000freetools.com/disclaimer",
  "https://1000freetools.com/explore-all-tools",
  "https://1000freetools.com/image-tools/add-watermark-on-image",
  "https://1000freetools.com/image-tools/background-remover",
  "https://1000freetools.com/image-tools/blur-image",
  "https://1000freetools.com/image-tools/crop-image",
  "https://1000freetools.com/image-tools/image-compressor",
  "https://1000freetools.com/image-tools/image-editor",
  "https://1000freetools.com/image-tools/image-filters",
  "https://1000freetools.com/image-tools/image-format-conversions",
  "https://1000freetools.com/image-tools/image-to-gif",
  "https://1000freetools.com/image-tools/image-to-pdf",
  "https://1000freetools.com/image-tools",
  "https://1000freetools.com/image-tools/pick-color-code-from-image",
  "https://1000freetools.com/image-tools/resize-image-dimensions",
  "https://1000freetools.com/image-tools/sharpen-image",
  "https://1000freetools.com/json-tools/csv-to-json",
  "https://1000freetools.com/json-tools/jmespath-query",
  "https://1000freetools.com/json-tools/json-api-error-formatter",
  "https://1000freetools.com/json-tools/json-api-formatter",
  "https://1000freetools.com/json-tools/json-api-response-generator",
  "https://1000freetools.com/json-tools/json-array-generator",
  "https://1000freetools.com/json-tools/json-array-object-counter",
  "https://1000freetools.com/json-tools/json-axios-code-generator",
  "https://1000freetools.com/json-tools/json-base64",
  "https://1000freetools.com/json-tools/json-config-validator",
  "https://1000freetools.com/json-tools/json-datetime-generator",
  "https://1000freetools.com/json-tools/json-depth-analyzer",
  "https://1000freetools.com/json-tools/json-diff",
  "https://1000freetools.com/json-tools/json-duplicate-key-finder",
  "https://1000freetools.com/json-tools/json-empty-field-finder",
  "https://1000freetools.com/json-tools/json-encode-decode",
  "https://1000freetools.com/json-tools/json-enum-generator",
  "https://1000freetools.com/json-tools/json-env-converter",
  "https://1000freetools.com/json-tools/json-error-explanation",
  "https://1000freetools.com/json-tools/json-escape-unescape",
  "https://1000freetools.com/json-tools/json-explainer",
  "https://1000freetools.com/json-tools/json-extract-subjson",
  "https://1000freetools.com/json-tools/json-fetch-code-generator",
  "https://1000freetools.com/json-tools/json-filter",
  "https://1000freetools.com/json-tools/json-flatten",
  "https://1000freetools.com/json-tools/json-formatter-beautifier",
  "https://1000freetools.com/json-tools/json-jwt-decoder",
  "https://1000freetools.com/json-tools/json-key-extractor",
  "https://1000freetools.com/json-tools/json-key-frequency",
  "https://1000freetools.com/json-tools/json-key-value-extractor",
  "https://1000freetools.com/json-tools/json-linter",
  "https://1000freetools.com/json-tools/json-map-reduce",
  "https://1000freetools.com/json-tools/json-merge",
  "https://1000freetools.com/json-tools/json-minifier",
  "https://1000freetools.com/json-tools/json-nested-structure",
  "https://1000freetools.com/json-tools/json-obfuscator",
  "https://1000freetools.com/json-tools/json-pagination-generator",
  "https://1000freetools.com/json-tools/json-patch-generator",
  "https://1000freetools.com/json-tools/json-playground",
  "https://1000freetools.com/json-tools/json-pretty-print",
  "https://1000freetools.com/json-tools/json-random-object",
  "https://1000freetools.com/json-tools/json-remove-keys",
  "https://1000freetools.com/json-tools/json-rename-keys",
  "https://1000freetools.com/json-tools/json-schema-example-generator",
  "https://1000freetools.com/json-tools/json-schema-validator",
  "https://1000freetools.com/json-tools/json-sensitive-data-maser",
  "https://1000freetools.com/json-tools/json-size-calculator",
  "https://1000freetools.com/json-tools/json-sorter",
  "https://1000freetools.com/json-tools/json-step-by-step-parser",
  "https://1000freetools.com/json-tools/json-stringify-parse",
  "https://1000freetools.com/json-tools/json-structure-visualizer",
  "https://1000freetools.com/json-tools/json-to-csharp",
  "https://1000freetools.com/json-tools/json-to-csv",
  "https://1000freetools.com/json-tools/json-to-excel",
  "https://1000freetools.com/json-tools/json-to-go",
  "https://1000freetools.com/json-tools/json-to-graphql",
  "https://1000freetools.com/json-tools/json-to-java",
  "https://1000freetools.com/json-tools/json-to-javascript",
  "https://1000freetools.com/json-tools/json-to-kotlin",
  "https://1000freetools.com/json-tools/json-to-markdown-table",
  "https://1000freetools.com/json-tools/json-to-mongodb",
  "https://1000freetools.com/json-tools/json-to-php",
  "https://1000freetools.com/json-tools/json-to-python",
  "https://1000freetools.com/json-tools/json-to-sql-insert",
  "https://1000freetools.com/json-tools/json-to-swift",
  "https://1000freetools.com/json-tools/json-to-text",
  "https://1000freetools.com/json-tools/json-to-tsv",
  "https://1000freetools.com/json-tools/json-to-typescript",
  "https://1000freetools.com/json-tools/json-to-xml",
  "https://1000freetools.com/json-tools/json-to-yaml",
  "https://1000freetools.com/json-tools/json-transformer",
  "https://1000freetools.com/json-tools/json-unflatten",
  "https://1000freetools.com/json-tools/json-validator",
  "https://1000freetools.com/json-tools/json-value-search",
  "https://1000freetools.com/json-tools/json-viewer",
  "https://1000freetools.com/json-tools/jsonpath-query",
  "https://1000freetools.com/json-tools",
  "https://1000freetools.com/json-tools/xml-to-json",
  "https://1000freetools.com/json-tools/yaml-to-json",
  "https://1000freetools.com/math-tools/2d-function-plotter",
  "https://1000freetools.com/math-tools/absolute-value-calculator",
  "https://1000freetools.com/math-tools/age-calculator",
  "https://1000freetools.com/math-tools/angle-calculator",
  "https://1000freetools.com/math-tools/angle-elevation-depression-solver",
  "https://1000freetools.com/math-tools/annuity-calculator",
  "https://1000freetools.com/math-tools/antilogarithm-calculator",
  "https://1000freetools.com/math-tools/area-calculator",
  "https://1000freetools.com/math-tools/area-converter",
  "https://1000freetools.com/math-tools/arithmetic-sequence-calculator",
  "https://1000freetools.com/math-tools/arithmetic-series-calculator",
  "https://1000freetools.com/math-tools/armstrong-number-checker",
  "https://1000freetools.com/math-tools/average-calculator",
  "https://1000freetools.com/math-tools/bar-chart-builder",
  "https://1000freetools.com/math-tools/big-number-calculator",
  "https://1000freetools.com/math-tools/binary-arithmetic-calculator",
  "https://1000freetools.com/math-tools/binomial-expansion-calculator",
  "https://1000freetools.com/math-tools/bitwise-operations-calculator",
  "https://1000freetools.com/math-tools/boolean-expression-evaluator",
  "https://1000freetools.com/math-tools/box-plot-generator",
  "https://1000freetools.com/math-tools/break-even-point-calculator",
  "https://1000freetools.com/math-tools/cartesian-product-calculator",
  "https://1000freetools.com/math-tools/circle-calculator",
  "https://1000freetools.com/math-tools/combination-calculator",
  "https://1000freetools.com/math-tools/complement-of-set-calculator",
  "https://1000freetools.com/math-tools/compound-interest-calculator",
  "https://1000freetools.com/math-tools/confidence-interval-calculator",
  "https://1000freetools.com/math-tools/coordinate-geometry-calculator",
  "https://1000freetools.com/math-tools/coordinate-plane-plotter",
  "https://1000freetools.com/math-tools/correlation-coefficient-calculator",
  "https://1000freetools.com/math-tools/currency-exchange-calculator",
  "https://1000freetools.com/math-tools/data-storage-converter",
  "https://1000freetools.com/math-tools/date-arithmetic-calculator",
  "https://1000freetools.com/math-tools/date-difference-calculator",
  "https://1000freetools.com/math-tools/day-of-week-calculator",
  "https://1000freetools.com/math-tools/days-until-since-calculator",
  "https://1000freetools.com/math-tools/decimal-to-fraction-converter",
  "https://1000freetools.com/math-tools/definite-integral-calculator",
  "https://1000freetools.com/math-tools/degrees-radians-converter",
  "https://1000freetools.com/math-tools/derivative-calculator",
  "https://1000freetools.com/math-tools/dice-roller",
  "https://1000freetools.com/math-tools/difference-of-sets-calculator",
  "https://1000freetools.com/math-tools/digit-sum-calculator",
  "https://1000freetools.com/math-tools/discount-markup-calculator",
  "https://1000freetools.com/math-tools/distance-between-two-points-calculator",
  "https://1000freetools.com/math-tools/divisibility-check-2-20",
  "https://1000freetools.com/math-tools/divisibility-checker",
  "https://1000freetools.com/math-tools/eigenvalue-calculator",
  "https://1000freetools.com/math-tools/emi-loan-calculator",
  "https://1000freetools.com/math-tools/energy-converter",
  "https://1000freetools.com/math-tools/equation-balancer",
  "https://1000freetools.com/math-tools/estimation-rounding-tool",
  "https://1000freetools.com/math-tools/eulers-totient-calculator",
  "https://1000freetools.com/math-tools/expand-simplify-binomials",
  "https://1000freetools.com/math-tools/exponent-calculator",
  "https://1000freetools.com/math-tools/factor-calculator",
  "https://1000freetools.com/math-tools/factorial-calculator",
  "https://1000freetools.com/math-tools/factors-list-generator",
  "https://1000freetools.com/math-tools/fibonacci-generator",
  "https://1000freetools.com/math-tools/five-number-summary-calculator",
  "https://1000freetools.com/math-tools/fraction-calculator",
  "https://1000freetools.com/math-tools/fraction-to-decimal-converter",
  "https://1000freetools.com/math-tools/frequency-distribution-table",
  "https://1000freetools.com/math-tools/future-value-calculator",
  "https://1000freetools.com/math-tools/gcd-hcf-calculator",
  "https://1000freetools.com/math-tools/geometric-mean-calculator",
  "https://1000freetools.com/math-tools/geometric-sequence-calculator",
  "https://1000freetools.com/math-tools/geometric-series-calculator",
  "https://1000freetools.com/math-tools/gpa-calculator",
  "https://1000freetools.com/math-tools/gradient-slope-calculator",
  "https://1000freetools.com/math-tools/harmonic-mean-calculator",
  "https://1000freetools.com/math-tools/harmonic-series-calculator",
  "https://1000freetools.com/math-tools/histogram-generator",
  "https://1000freetools.com/math-tools/identity-matrix-generator",
  "https://1000freetools.com/math-tools/inequality-solver",
  "https://1000freetools.com/math-tools/intersection-of-sets-calculator",
  "https://1000freetools.com/math-tools/inverse-trig-calculator",
  "https://1000freetools.com/math-tools/law-of-cosines-calculator",
  "https://1000freetools.com/math-tools/law-of-sines-calculator",
  "https://1000freetools.com/math-tools/lcm-calculator",
  "https://1000freetools.com/math-tools/leap-year-checker",
  "https://1000freetools.com/math-tools/length-converter",
  "https://1000freetools.com/math-tools/limit-calculator",
  "https://1000freetools.com/math-tools/line-graph-builder",
  "https://1000freetools.com/math-tools/linear-equation-solver",
  "https://1000freetools.com/math-tools/linear-regression-calculator",
  "https://1000freetools.com/math-tools/logarithm-calculator",
  "https://1000freetools.com/math-tools/logic-gate-simulator",
  "https://1000freetools.com/math-tools/long-division-calculator",
  "https://1000freetools.com/math-tools/long-multiplication-calculator",
  "https://1000freetools.com/math-tools/magic-square-generator",
  "https://1000freetools.com/math-tools/matrix-addition-subtraction-calculator",
  "https://1000freetools.com/math-tools/matrix-determinant-calculator",
  "https://1000freetools.com/math-tools/matrix-inverse-calculator",
  "https://1000freetools.com/math-tools/matrix-multiplication-calculator",
  "https://1000freetools.com/math-tools/matrix-rank-calculator",
  "https://1000freetools.com/math-tools/matrix-trace-calculator",
  "https://1000freetools.com/math-tools/matrix-transpose-calculator",
  "https://1000freetools.com/math-tools/mean-median-mode-calculator",
  "https://1000freetools.com/math-tools/midpoint-calculator",
  "https://1000freetools.com/math-tools/mixed-number-calculator",
  "https://1000freetools.com/math-tools/modular-arithmetic-calculator",
  "https://1000freetools.com/math-tools/modulo-calculator",
  "https://1000freetools.com/math-tools/multiplication-table",
  "https://1000freetools.com/math-tools/normal-distribution-calculator",
  "https://1000freetools.com/math-tools/nth-term-finder",
  "https://1000freetools.com/math-tools/number-base-converter",
  "https://1000freetools.com/math-tools/number-line-visualizer",
  "https://1000freetools.com/math-tools/number-sorter",
  "https://1000freetools.com/math-tools/number-word-converter",
  "https://1000freetools.com/math-tools/order-of-operations-solver",
  "https://1000freetools.com/math-tools/outlier-detector",
  "https://1000freetools.com/math-tools",
  "https://1000freetools.com/math-tools/palindrome-number-checker",
  "https://1000freetools.com/math-tools/pascals-triangle-generator",
  "https://1000freetools.com/math-tools/percentage-calculator",
  "https://1000freetools.com/math-tools/percentage-change-calculator",
  "https://1000freetools.com/math-tools/perfect-number-checker",
  "https://1000freetools.com/math-tools/perimeter-calculator",
  "https://1000freetools.com/math-tools/permutation-calculator",
  "https://1000freetools.com/math-tools/pi-digit-generator",
  "https://1000freetools.com/math-tools/pie-bar-chart-generator",
  "https://1000freetools.com/math-tools/pie-chart-builder",
  "https://1000freetools.com/math-tools/polygon-interior-angle-sum-calculator",
  "https://1000freetools.com/math-tools/polynomial-evaluator",
  "https://1000freetools.com/math-tools/power-set-generator",
  "https://1000freetools.com/math-tools/present-value-calculator",
  "https://1000freetools.com/math-tools/pressure-converter",
  "https://1000freetools.com/math-tools/prime-factorization-calculator",
  "https://1000freetools.com/math-tools/prime-number-checker",
  "https://1000freetools.com/math-tools/probability-calculator",
  "https://1000freetools.com/math-tools/profit-loss-calculator",
  "https://1000freetools.com/math-tools/pythagorean-theorem-calculator",
  "https://1000freetools.com/math-tools/quadratic-equation-solver",
  "https://1000freetools.com/math-tools/random-number-generator",
  "https://1000freetools.com/math-tools/ratio-calculator",
  "https://1000freetools.com/math-tools/reverse-number",
  "https://1000freetools.com/math-tools/riemann-sum-calculator",
  "https://1000freetools.com/math-tools/right-triangle-calculator",
  "https://1000freetools.com/math-tools/roi-calculator",
  "https://1000freetools.com/math-tools/roman-numeral-converter",
  "https://1000freetools.com/math-tools/rounding-calculator",
  "https://1000freetools.com/math-tools/sales-tax-vat-calculator",
  "https://1000freetools.com/math-tools/scalar-multiplication-calculator",
  "https://1000freetools.com/math-tools/scatter-plot-generator",
  "https://1000freetools.com/math-tools/scientific-calculator",
  "https://1000freetools.com/math-tools/scientific-notation-converter",
  "https://1000freetools.com/math-tools/significant-figures-calculator",
  "https://1000freetools.com/math-tools/simple-interest-calculator",
  "https://1000freetools.com/math-tools/simplify-expression",
  "https://1000freetools.com/math-tools/slope-calculator",
  "https://1000freetools.com/math-tools/speed-converter",
  "https://1000freetools.com/math-tools/square-root-calculator",
  "https://1000freetools.com/math-tools/standard-calculator",
  "https://1000freetools.com/math-tools/standard-deviation-variance-calculator",
  "https://1000freetools.com/math-tools/subset-checker",
  "https://1000freetools.com/math-tools/sudoku-validator",
  "https://1000freetools.com/math-tools/surface-area-calculator",
  "https://1000freetools.com/math-tools/system-of-equations-solver",
  "https://1000freetools.com/math-tools/tangent-line-calculator",
  "https://1000freetools.com/math-tools/taylor-series-approximation",
  "https://1000freetools.com/math-tools/temperature-converter",
  "https://1000freetools.com/math-tools/time-converter",
  "https://1000freetools.com/math-tools/time-duration-calculator",
  "https://1000freetools.com/math-tools/tip-calculator",
  "https://1000freetools.com/math-tools/triangle-solver",
  "https://1000freetools.com/math-tools/trig-function-calculator",
  "https://1000freetools.com/math-tools/trig-identity-verifier",
  "https://1000freetools.com/math-tools/truth-table-generator",
  "https://1000freetools.com/math-tools/twos-complement-calculator",
  "https://1000freetools.com/math-tools/union-of-sets-calculator",
  "https://1000freetools.com/math-tools/unit-circle-reference",
  "https://1000freetools.com/math-tools/venn-diagram-tool",
  "https://1000freetools.com/math-tools/volume-calculator",
  "https://1000freetools.com/math-tools/volume-converter",
  "https://1000freetools.com/math-tools/weight-converter",
  "https://1000freetools.com/math-tools/weighted-average-calculator",
  "https://1000freetools.com/math-tools/z-score-calculator",
  "https://1000freetools.com/",
  "https://1000freetools.com/privacy-policy",
  "https://1000freetools.com/terms",
  "https://1000freetools.com/text-tools",
  "https://1000freetools.com/unit-converters/acceleration",
  "https://1000freetools.com/unit-converters/acceleration-angular",
  "https://1000freetools.com/unit-converters/age-calculator",
  "https://1000freetools.com/unit-converters/angle",
  "https://1000freetools.com/unit-converters/apparent-magnitude-converter",
  "https://1000freetools.com/unit-converters/area",
  "https://1000freetools.com/unit-converters/astronomical-unit-converter",
  "https://1000freetools.com/unit-converters/audio-bitrate-converter",
  "https://1000freetools.com/unit-converters/baking-pan-size-converter",
  "https://1000freetools.com/unit-converters/bmi-calculator",
  "https://1000freetools.com/unit-converters/brick-calculator",
  "https://1000freetools.com/unit-converters/calorie-burn-rate-converter",
  "https://1000freetools.com/unit-converters/cement-sand-aggregate-converter",
  "https://1000freetools.com/unit-converters/charge",
  "https://1000freetools.com/unit-converters/clothing-size-converter",
  "https://1000freetools.com/unit-converters/concentration-molar",
  "https://1000freetools.com/unit-converters/concentration-solution",
  "https://1000freetools.com/unit-converters/concrete-mix-ratio-converter",
  "https://1000freetools.com/unit-converters/concrete-volume-converter",
  "https://1000freetools.com/unit-converters/cups-to-grams",
  "https://1000freetools.com/unit-converters/cups-to-ml",
  "https://1000freetools.com/unit-converters/current",
  "https://1000freetools.com/unit-converters/data-storage",
  "https://1000freetools.com/unit-converters/date-difference-calculator",
  "https://1000freetools.com/unit-converters/density",
  "https://1000freetools.com/unit-converters/dew-point-calculator",
  "https://1000freetools.com/unit-converters/digital-image-resolution",
  "https://1000freetools.com/unit-converters/electric-conductance",
  "https://1000freetools.com/unit-converters/electric-conductivity",
  "https://1000freetools.com/unit-converters/electric-field-strength",
  "https://1000freetools.com/unit-converters/electric-potential",
  "https://1000freetools.com/unit-converters/electric-resistance",
  "https://1000freetools.com/unit-converters/electric-resistivity",
  "https://1000freetools.com/unit-converters/electrostatic-capacitance",
  "https://1000freetools.com/unit-converters/energy",
  "https://1000freetools.com/unit-converters/exposure-dose-converter",
  "https://1000freetools.com/unit-converters/fabric-gsm-converter",
  "https://1000freetools.com/unit-converters/floor-area-converter",
  "https://1000freetools.com/unit-converters/flow",
  "https://1000freetools.com/unit-converters/flow-mass",
  "https://1000freetools.com/unit-converters/flow-molar",
  "https://1000freetools.com/unit-converters/force",
  "https://1000freetools.com/unit-converters/frequency",
  "https://1000freetools.com/unit-converters/frequency-to-musical-note-converter",
  "https://1000freetools.com/unit-converters/fuel-consumption",
  "https://1000freetools.com/unit-converters/fuel-efficiency-mass",
  "https://1000freetools.com/unit-converters/fuel-efficiency-volume",
  "https://1000freetools.com/unit-converters/heat-density",
  "https://1000freetools.com/unit-converters/heat-flux-density",
  "https://1000freetools.com/unit-converters/heat-transfer-coefficient",
  "https://1000freetools.com/unit-converters/height-converter",
  "https://1000freetools.com/unit-converters/horsepower-to-animals-converter",
  "https://1000freetools.com/unit-converters/humidity-ratio-converter",
  "https://1000freetools.com/unit-converters/illumination",
  "https://1000freetools.com/unit-converters/image-dpi-converter",
  "https://1000freetools.com/unit-converters/inductance",
  "https://1000freetools.com/unit-converters/ingredient-density-converter",
  "https://1000freetools.com/unit-converters/length",
  "https://1000freetools.com/unit-converters/light-years-to-parsecs",
  "https://1000freetools.com/unit-converters/linear-charge-density",
  "https://1000freetools.com/unit-converters/linear-current-density",
  "https://1000freetools.com/unit-converters/lumber-board-feet-converter",
  "https://1000freetools.com/unit-converters/luminance",
  "https://1000freetools.com/unit-converters/luminous-intensity",
  "https://1000freetools.com/unit-converters/magnetic-field-strength",
  "https://1000freetools.com/unit-converters/magnetic-flux",
  "https://1000freetools.com/unit-converters/magnetic-flux-density",
  "https://1000freetools.com/unit-converters/magnetomotive-force",
  "https://1000freetools.com/unit-converters/mass-flux-density",
  "https://1000freetools.com/unit-converters/moment-of-force",
  "https://1000freetools.com/unit-converters/moment-of-inertia",
  "https://1000freetools.com/unit-converters/oven-temperature-converter",
  "https://1000freetools.com/unit-converters",
  "https://1000freetools.com/unit-converters/permeability",
  "https://1000freetools.com/unit-converters/planet-weight-converter",
  "https://1000freetools.com/unit-converters/power",
  "https://1000freetools.com/unit-converters/pressure",
  "https://1000freetools.com/unit-converters/radiation-dose-converter",
  "https://1000freetools.com/unit-converters/radioactivity-converter",
  "https://1000freetools.com/unit-converters/rainfall-converter",
  "https://1000freetools.com/unit-converters/rebar-weight-calculator",
  "https://1000freetools.com/unit-converters/ring-size-converter",
  "https://1000freetools.com/unit-converters/roofing-sheet-coverage-converter",
  "https://1000freetools.com/unit-converters/running-pace-to-speed-converter",
  "https://1000freetools.com/unit-converters/shoe-size-converter",
  "https://1000freetools.com/unit-converters/sound-pressure-pa-to-db",
  "https://1000freetools.com/unit-converters/sourdough-hydration-converter",
  "https://1000freetools.com/unit-converters/specific-heat-capacity",
  "https://1000freetools.com/unit-converters/specific-volume",
  "https://1000freetools.com/unit-converters/speed",
  "https://1000freetools.com/unit-converters/surface-charge-density",
  "https://1000freetools.com/unit-converters/surface-current-density",
  "https://1000freetools.com/unit-converters/surface-tension",
  "https://1000freetools.com/unit-converters/temperature",
  "https://1000freetools.com/unit-converters/temperature-interval",
  "https://1000freetools.com/unit-converters/thermal-conductivity",
  "https://1000freetools.com/unit-converters/thermal-expansion",
  "https://1000freetools.com/unit-converters/thermal-resistance",
  "https://1000freetools.com/unit-converters/thread-count-converter",
  "https://1000freetools.com/unit-converters/tile-calculator",
  "https://1000freetools.com/unit-converters/time",
  "https://1000freetools.com/unit-converters/time-duration-calculator",
  "https://1000freetools.com/unit-converters/torque",
  "https://1000freetools.com/unit-converters/unix-timestamp-converter",
  "https://1000freetools.com/unit-converters/velocity-angular",
  "https://1000freetools.com/unit-converters/video-frame-rate-converter",
  "https://1000freetools.com/unit-converters/viscosity-dynamic",
  "https://1000freetools.com/unit-converters/viscosity-kinematic",
  "https://1000freetools.com/unit-converters/volume",
  "https://1000freetools.com/unit-converters/volume-charge-density",
  "https://1000freetools.com/unit-converters/volume-dry",
  "https://1000freetools.com/unit-converters/wavelength",
  "https://1000freetools.com/unit-converters/weight-and-mass",
  "https://1000freetools.com/unit-converters/wind-speed-converter",
  "https://1000freetools.com/video-tools/change-video-fps",
  "https://1000freetools.com/video-tools/crop-video",
  "https://1000freetools.com/video-tools/enhance-video-quality",
  "https://1000freetools.com/video-tools/extract-audio-from-video",
  "https://1000freetools.com/video-tools",
  "https://1000freetools.com/video-tools/resize-video-dimensions",
  "https://1000freetools.com/video-tools/rotate-video",
  "https://1000freetools.com/video-tools/video-color-space-transformation",
  "https://1000freetools.com/video-tools/video-compressor",
  "https://1000freetools.com/video-tools/video-format-converter",
  "https://1000freetools.com/video-tools/video-grayscale",
  "https://1000freetools.com/video-tools/video-metadata-viewer",
  "https://1000freetools.com/video-tools/video-overlays",
  "https://1000freetools.com/video-tools/video-player",
  "https://1000freetools.com/video-tools/video-transparency-maker"
];


const res = await fetch("https://api.indexnow.org/indexnow", {
  method: "POST",
  headers: { "Content-Type": "application/json" },
  body: JSON.stringify({
    host: "1000freetools.com",
    key: "f7dd6e8f72054d3c9673eb39d3a7da3f",
    urlList: urls,
  }),
});

const text = await res.text();
console.log(res.status, text);
